name: Junkibu
favicon: null
layout_spectrum: 0.5332880562637001
typography_spectrum: 0.15458721155300736
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.34658556268550456
  lightness: 0.7514858825597912
  saturation: 0.28159035416319966
  rhythmicContrast: 0.19679887359961867
purpose: []
